# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus-donation-app

# JPA/Hibernate
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.log.sql=false

# App
quarkus.application.name=quarkus-donation-app
quarkus.application.version=1.0.0

# PayPal Auth
paypal.client.id=${PAYPAL_CLIENT_ID}
paypal.client.secret=${PAYPAL_CLIENT_SECRET}

# PayPal REST Client
quarkus.rest-client.paypal.url=https://api-m.sandbox.paypal.com

# Application Base URL
app.base-url=http://localhost:8080

# Dev Mode
%dev.quarkus.http.port=8080
%dev.quarkus.log.level=INFO
