# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=root
quarkus.datasource.password=root
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus-donation-app

# JPA/Hibernate
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=true

# App
quarkus.application.name=quarkus-donation-app
quarkus.application.version=1.0.0

# Dev Mode
%dev.quarkus.http.port=8080
%dev.quarkus.log.level=INFO
