DROP TABLE IF EXISTS donations CASCADE;

CREATE TABLE donations
(
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    donor_name            VARCHAR(255)   NOT NULL,
    donor_email           VARCHAR(255)   NOT NULL,
    amount                DECIMAL(19, 2) NOT NULL,
    message               TEXT,
    paypal_order_id       VARCHAR(255),
    paypal_transaction_id VARCHAR(255),
    paypal_email          VARCHAR(255),
    paypal_amount         DECIMAL(19, 2),
    paypal_currency       VARCHAR(3),
    paypal_status         VARCHAR(50),
    paypal_response_data  TEXT,
    paypal_error_message  TEXT,
    paypal_created_at     TIMESTAMP,
    paypal_updated_at     TIMESTAMP,
    created_at            TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP,

    CONSTRAINT amount_positive CHECK (amount > 0)
);

CREATE INDEX IF NOT EXISTS idx_donor_email ON donations (donor_email);
CREATE INDEX IF NOT EXISTS idx_paypal_order_id ON donations (paypal_order_id);
CREATE INDEX IF NOT EXISTS idx_paypal_status ON donations (paypal_status);
CREATE INDEX IF NOT EXISTS idx_created_at ON donations (created_at DESC);